/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: anybody (https://sketchfab.com/anybody)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-board-and-figures-d6d3cd6d2d2a4a13bd16d0667410cf1e
Title: Chess Board And Figures
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
	nodes: {
		Object_4: THREE.Mesh
		Object_5: THREE.Mesh
		Object_6: THREE.Mesh
		Object_8: THREE.Mesh
		Object_10: THREE.Mesh
		Object_12: THREE.Mesh
		Object_14: THREE.Mesh
		Object_16: THREE.Mesh
		Object_18: THREE.Mesh
		Object_20: THREE.Mesh
		Object_22: THREE.Mesh
		Object_24: THREE.Mesh
		Object_26: THREE.Mesh
		Object_28: THREE.Mesh
		Object_30: THREE.Mesh
		Object_32: THREE.Mesh
		Object_34: THREE.Mesh
		Object_36: THREE.Mesh
		Object_38: THREE.Mesh
		Object_40: THREE.Mesh
		Object_42: THREE.Mesh
		Object_44: THREE.Mesh
		Object_46: THREE.Mesh
		Object_48: THREE.Mesh
		Object_50: THREE.Mesh
		Object_52: THREE.Mesh
		Object_54: THREE.Mesh
		Object_56: THREE.Mesh
		Object_58: THREE.Mesh
		Object_60: THREE.Mesh
		Object_62: THREE.Mesh
		Object_64: THREE.Mesh
		Object_66: THREE.Mesh
		Object_68: THREE.Mesh
		Object_70: THREE.Mesh
	}
	materials: {
		Material_37: THREE.MeshStandardMaterial
		Material_36: THREE.MeshStandardMaterial
		['Material.001']: THREE.MeshStandardMaterial
		['Figures.Black']: THREE.MeshStandardMaterial
		['Figures.White']: THREE.MeshStandardMaterial
	}
}

interface IPositions {
	globalBoardPositions: { [key: string]: number[] }
	setChessMoveToSubmitToGame: any
}

export function Board(props: JSX.IntrinsicElements['group'] & IPositions) {
	const { nodes, materials } = useGLTF(
		'./chess_board_and_figures.glb'
	) as GLTFResult

	const { globalBoardPositions, setChessMoveToSubmitToGame } = props
	return (
		<group
			{...props}
			dispose={null}
		>
			<group
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={2}
				position={[0, -0.1, 0]}
			>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group
						position={[0, -0.043, 0]}
						scale={0.025}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.Object_4.geometry}
							material={materials.Material_37}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.Object_5.geometry}
							material={materials.Material_36}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.Object_6.geometry}
							material={materials['Material.001']}
						/>
					</group>
					<mesh
						castShadow
						receiveShadow
						name='BlackKing'
						geometry={nodes.Object_8.geometry}
						material={materials['Figures.Black']}
						position={[
							globalBoardPositions.blackKing[0],
							0.616,
							globalBoardPositions.blackKing[1],
						]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={[-0.034, 0.034, 0.034]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='BlackQueen'
						geometry={nodes.Object_10.geometry}
						material={materials['Figures.Black']}
						position={[
							globalBoardPositions.blackQueen[0],
							0.444,
							globalBoardPositions.blackQueen[1],
						]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={[-0.034, 0.034, 0.034]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_12.geometry}
						material={materials['Figures.Black']}
						position={[0.761, 0.302, 1.772]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={0.034}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_14.geometry}
						material={materials['Figures.Black']}
						position={[1.275, 0.304, 1.787]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={0.034}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_16.geometry}
						material={materials['Figures.Black']}
						position={[1.775, 0.246, 1.773]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={0.034}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_18.geometry}
						material={materials['Figures.Black']}
						position={[1.776, 0.165, 1.292]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_20.geometry}
						material={materials['Figures.Black']}
						position={[1.276, 0.165, 1.292]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_22.geometry}
						material={materials['Figures.Black']}
						position={[0.776, 0.165, 1.292]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_24.geometry}
						material={materials['Figures.Black']}
						position={[0.276, 0.165, 1.292]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_26.geometry}
						material={materials['Figures.Black']}
						position={[-0.264, 0.165, 1.292]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_28.geometry}
						material={materials['Figures.Black']}
						position={[-0.764, 0.165, 1.292]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_30.geometry}
						material={materials['Figures.Black']}
						position={[-1.264, 0.165, 1.292]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_32.geometry}
						material={materials['Figures.Black']}
						position={[-1.764, 0.165, 1.292]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_34.geometry}
						material={materials['Figures.Black']}
						position={[-0.769, 0.302, 1.792]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={0.034}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_36.geometry}
						material={materials['Figures.Black']}
						position={[-1.255, 0.304, 1.807]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={0.034}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_38.geometry}
						material={materials['Figures.Black']}
						position={[-1.755, 0.246, 1.793]}
						rotation={[Math.PI / 2, 0, -Math.PI]}
						scale={0.034}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_40.geometry}
						material={materials['Figures.White']}
						position={[0.242, 0.616, -1.773]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={[-0.034, 0.034, 0.034]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_42.geometry}
						material={materials['Figures.White']}
						position={[-0.261, 0.444, -1.773]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={[-0.034, 0.034, 0.034]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_44.geometry}
						material={materials['Figures.White']}
						position={[-0.766, 0.302, -1.772]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={0.034}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_46.geometry}
						material={materials['Figures.White']}
						position={[-1.28, 0.304, -1.787]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={0.034}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_48.geometry}
						material={materials['Figures.White']}
						position={[-1.78, 0.246, -1.773]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={0.034}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_50.geometry}
						material={materials['Figures.White']}
						position={[-1.781, 0.165, -1.253]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_52.geometry}
						material={materials['Figures.White']}
						position={[0.784, 0.302, -1.772]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={0.034}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_54.geometry}
						material={materials['Figures.White']}
						position={[1.27, 0.304, -1.787]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={0.034}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_56.geometry}
						material={materials['Figures.White']}
						position={[1.79, 0.246, -1.773]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={0.034}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_58.geometry}
						material={materials['Figures.White']}
						position={[-1.281, 0.165, -1.253]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_60.geometry}
						material={materials['Figures.White']}
						position={[-0.781, 0.165, -1.253]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_62.geometry}
						material={materials['Figures.White']}
						position={[-0.241, 0.165, -1.273]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_64.geometry}
						material={materials['Figures.White']}
						position={[0.259, 0.165, -1.273]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_66.geometry}
						material={materials['Figures.White']}
						position={[0.759, 0.165, -1.273]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Object_68.geometry}
						material={materials['Figures.White']}
						position={[1.259, 0.165, -1.273]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={[-0.025, 0.025, 0.025]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='whiteAPawn'
						geometry={nodes.Object_70.geometry}
						material={materials['Figures.White']}
						position={[
							globalBoardPositions.whiteAPawn[0],
							0.165,
							globalBoardPositions.whiteAPawn[1],
						]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={[-0.025, 0.025, 0.025]}
						onClick={(e) => {
							e.stopPropagation()
							setChessMoveToSubmitToGame({
								piece: '',
								pieceName: 'whiteAPawn',
								coord: '',
								readyToSubmit: false,
							})
						}}
					/>
				</group>
			</group>
		</group>
	)
}

export default Board

useGLTF.preload('/chess_board_and_figures.glb')
